FROM php:8.3-cli
RUN apt-get update && apt-get install -y libicu-dev git unzip zip libsqlite3-dev libzip-dev curl gnupg
RUN curl -fsSL https://deb.nodesource.com/setup_20.x | bash - && apt-get install -y nodejs
RUN docker-php-ext-configure intl && docker-php-ext-install intl pdo pdo_sqlite pdo_mysql zip
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer
WORKDIR /app
